### ISSUE TITLE
HG002 Tandem rpeats annotation

### ISSUE THREAD

**Issue by Lionward** [ACEnglish/adotto#1]
Hi, I am sorry for the question, but I tried to find the Tandem repeats annotation file for the sample HG002, would you mind pointing that out for me if it does exist, since I wasn't successfull yet, I did find the one here which seems to be a catalog of Tandem repeats generated by TRF and restructured (correct me please if I am wrong).

https://zenodo.org/record/7689784

**Comment by ACEnglish** [comment]
The catalog you found is the reference annotation of Tandem Repeat regions. Technically that is all TRs inside of HG002 with the exception of reference regions absent from HG002's genome. I believe what you're looking for is the subset of these sites which vary from the reference in HG002 - a.k.a. HG002 Tandem Repeat expansions/contractions. Currently HG002 variants are bundled in the pVCF linked [here](https://github.com/ACEnglish/adotto/blob/main/variants/DataDescription.md). However, this contains all variants and lacks any annotations about which are Tandem Repeat expansions/contractions. You'd need to do that intersecting/subsetting yourself.

**Comment by Lionward** [comment]
thank you, yeah you are right, I am looking for the ones that vary from the reference. Thank you for your reply.
