### ISSUE TITLE
How can users use this benchmark? 

### ISSUE THREAD

**Issue by YaCui** [ACEnglish/adotto#2]
Hi, 

Thanks for your work on the TRs catalog benchmark. I am wondering if you could provide a JSON format of your combined TRs catalog for ExpansionHunter.

It's useless if users cannot use this TRs catalog with the software(such as ExpansionHunter).

Thanks,
Ya

**Comment by ACEnglish** [comment]
Hello,

I am not the maintainer of ExpansionHunter. In development of this catalog/benchmark, the maintainers and users of multiple TR callers have found the catalog useful for application to their tools. Presumably the adotto TR catalog holds all the information needed such that it could be reformatted to ExpansionHunter's expected input. 

Have a great day,
~/Adam English

**Comment by YaCui** [comment]
Thanks for your quick response.
