### ISSUE TITLE
Benchmark of TRGT

### ISSUE THREAD

**Issue by CSU-KangHu** [ACEnglish/adotto#5]
Hello @ACEnglish,

Although I understand that TRGT is still in the development phase and not ready for benchmarking, I still want to test TRGT's performance in detecting TRs. I would like to follow your tutorial at https://github.com/ACEnglish/adotto/tree/main/benchmark/GIABTR_benchmark.6.26.

For the gold standard dataset, I downloaded `HG002_GRCh38_TandemRepeats_v1.0.bed.gz` and `HG002_GRCh38_TandemRepeats_v1.0.vcf.gz` as the gold standard from https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/AshkenazimTrio/HG002_NA24385_son/TandemRepeats_v1.0/GRCh38/.

I ran the TRGT command as follows:
```
trgt --genome ${pathTo}/hg38_chr1.fa --repeats  ${pathTo}/adotto_repeats.hg38.chr1.bed --reads  ${pathTo}/HG002.m84011_220902_175841_s1.GRCh38.chr1.bam --threads 20 --output-prefix HG002
```
Where `hg38_chr1.fa` is chromosome 1 of the hg38 reference genome; `adotto_repeats.hg38.chr1.bed` represents regions of chromosome 1 of `adotto_repeats.hg38.bed` from https://zenodo.org/records/8329210; `HG002.m84011_220902_175841_s1.GRCh38.chr1.bam` is the bam file of reads aligned to hg38 for HG002.

For evaluation, I used the following command:
```
truvari bench -b ${pathTo}/HG002_GRCh38_TandemRepeats_v1.0.chr1.vcf.gz -c ${pathTo}/HG002.sorted.split.vcf.gz --includebed ${pathTo}/HG002_GRCh38_TandemRepeats_v1.0.chr1.bed.gz --sizemin 5 --pick ac -o bench_result/
```
Where `HG002_GRCh38_TandemRepeats_v1.0.chr1.vcf.gz` is a subset of chromosome 1 extracted from `HG002_GRCh38_TandemRepeats_v1.0.vcf.gz`; `HG002.sorted.split.vcf.gz` separates the two alleles from the output result `HG002.vcf.gz` of TRGT; `HG002_GRCh38_TandemRepeats_v1.0.chr1.bed.gz` is a subset of chromosome 1 extracted from `HG002_GRCh38_TandemRepeats_v1.0.bed.gz`.

Experiment Results:
![image](https://github.com/ACEnglish/adotto/assets/22925278/4b48722c-f754-46ae-b973-1c0eab7ebbe9)

Why is the F1-score so low? Is there any issue with the command I ran?

**Comment by ACEnglish** [comment]
There is a README inside https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/AshkenazimTrio/HG002_NA24385_son/TandemRepeats_v1.0/GRCh38/

You ran the first step, `bench`, which will find variant representations that match. The second step, `refine`, will harmonize the variant representations with `phab` before re-matching. 

This low F1 happens because TRGT reports 'replacment' style entries while the benchmark has indels. These don't match match well without harmonization. For example: these are identical variants.

```
# indel
chr1    1234    .    A    ATATA
# replacement
chr1    1230    .    TATATATATA    TATATATATATATA
```

**Comment by CSU-KangHu** [comment]
Hi @ACEnglish,

Thank you for your prompt response. I have proceeded with the second step, `refine`. Currently, the results are as depicted in the following figure. Could you confirm if this falls within a reasonable range?

![image](https://github.com/ACEnglish/adotto/assets/22925278/23f37912-ae77-4a1b-9f1d-15f8a7e324f9)

Additionally, I have another question. Can SV detection tools identify TR variations? I attempted to use SVision for detection, and the results are illustrated in the following figure:

![image](https://github.com/ACEnglish/adotto/assets/22925278/db5e966b-154c-4480-b5ec-9fdf0dde34bb)

I observed that SVision failed to detect many of the `TP_TP_TP` sites marked in the `HG002_GRCh38_TandemRepeats_v1.0.bed.gz` file.

**Comment by ACEnglish** [comment]
I'm fairly certain that you're looking at `result/phab_bench/summary.json`. If this is the case, the image shows the performance of the subset of regions which were 'refined'. The full refine result, with performance metrics of regions after they were refined and those that did not need it, is in `result/refine.variant_summary.json`. See [Truvari wiki](https://github.com/ACEnglish/truvari/wiki/refine) for documentation.

As for SV callers detecting TRs: ~70% of SVs are tandem repeats [source](https://www.biorxiv.org/content/10.1101/2023.10.29.564632v1), so most SV callers do find them. However, they typically perform less well compared to TR specific callers. I have no experience with SVision so I'm unable to estimate if the numbers you're seeing are its expected performance over TRs. Plus, their tool appears to have been benchmarked without considering sequence similarity of events and by checking only ' closeness and size similarity to assess whether two events are identical' [source](https://www.nature.com/articles/s41592-022-01609-w). I believe sequence similarity is important for not over-estimating SV caller performance, particularly in TRs.
