### ISSUE TITLE
Format error of anno column in v1.2

### ISSUE THREAD

**Issue by Han-Cao** [ACEnglish/adotto#7]
Hi,

The anno column in release v1.2 has more quotes than expected by `truvari anno trf`, it also revert "repeat" to "motif"

For example, the first line of 1.1 and 1.2 are:
```
# v1.1
[{"chrom": "chr1", "start": 10000, "end": 10467, "period": 6.0, "copies": 77.2, "score": 1243, "entropy": 1.43, "ovl_flag": 1, "repeat": "TAACCC", "purity": 98}, {"chrom": "chr1", "start": 10481, "end": 10497, "period": 4.0, "copies": 4.2, "score": 41, "entropy": 0.94, "ovl_flag": 1, "repeat": "GCCC", "purity": 94}]

#v1.2
"[{""chrom"": ""chr1"", ""start"": 10000, ""end"": 10467, ""period"": 6.0, ""copies"": 77.2, ""score"": 1243, ""entropy"": 1.43, ""ovl_flag"": 1, ""motif"": ""TAACCC"", ""purity"": 98}, {""chrom"": ""chr1"", ""start"": 10481, ""end"": 10497, ""period"": 4.0, ""copies"": 4.2, ""score"": 41, ""entropy"": 0.94, ""ovl_flag"": 1, ""motif"": ""GCCC"", ""purity"": 94}]"
```

I generated a `truvari anno trf` compatible bed file by:
```
zcat adotto_TRregions_v1.2.bed.gz | cut -f1-3,18 | sed 's/"\[/[/g; s/"$//; s/""/"/g; s/"motif":/"repeat":/g' | bgzip > anno.trf.bed.gz
```

**Comment by ACEnglish** [comment]
Hello,

Thanks for reporting this and I apologize for the oversight. To fix this, I have:
1) Updated `truvari anno trf` to look for either the 'repeat' or 'motif' key in the provided annotation file. This is available now from the development branch and will
2) Uploaded a new patch of adotto v1.2.1 and updated relevant links in this repository
[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.13987414.svg)](https://doi.org/10.5281/zenodo.13987414)
3) Updated the truvari wiki to document adotto v1.2.1 and special notes for converting adotto v1.2 when using truvari ≤4.3.1

Have a great day,
~/Adam English
